#pragma once
#include "Source/Events/Event.h"
namespace Firelight::Events::Inv
{
	NEW_EVENT(UPDATEINV);
	NEW_EVENT(ADD_NEW_INV);
	NEW_EVENT(REMOVE_INV);


	
	NEW_EVENT(ADD_ITEM);
	NEW_EVENT(FINED_ITEM);

	NEW_EVENT(REMOVE_ITEM);
	NEW_EVENT(REMOVE_ITEM_TYPE);

	NEW_EVENT(GET_ITEM_TYPE);
	NEW_EVENT(GET_ITEM_TYPE_NUMBER);
	NEW_EVENT(GET_SPECIAL_SLOT);
	

	NEW_EVENT(LOAD_INVENTORY_GROUP);
	NEW_EVENT(UNLOAD_INVENTORY_GROUP);
	
}